/**
 * ─── Slate Icon Index ───
 * Centralized re-export of all Phosphor icons used in the app.
 * Pages import from '@/slate/icons' instead of '@phosphor-icons/react'.
 * This decouples the UI from a specific icon library and guarantees
 * consistent weight/style usage across every surface.
 */
export {
  Airplane,
  ArrowLeft,
  ArrowsDownUp,
  ArrowsLeftRight,
  CalendarBlank,
  Camera,
  Car,
  CaretDown,
  ChartBar,
  ChartLineUp,
  Check,
  Cube,
  CurrencyInr,
  DotsThreeCircle,
  EnvelopeSimple,
  Fingerprint,
  ForkKnife,
  House,
  ImageSquare,
  Info,
  Lightbulb,
  Lightning,
  Lock,
  Microphone,
  Money,
  Note,
  PaperPlaneTilt,
  PencilSimple,
  Phone,
  Plus,
  QrCode,
  Receipt,
  ShoppingBag,
  ShoppingCart,
  SignOut,
  Sparkle,
  Stethoscope,
  Tag,
  Ticket,
  Trash,
  TrendUp,
  User,
  Users,
  UsersThree,
  Cards,
  Textbox,
  CursorClick,
  Stack,
  ProjectorScreen,
  Palette,
  Wallet,
  X,
  Receipt as ReceiptIcon,
} from '@phosphor-icons/react';
